### ISSUE TITLE
Could you make create-t3-turbo

### ISSUE THREAD

**Issue by dayOneAbu** [exectx/t3-cloudflare#6]
t3-cloudflare was great but it would be best if you upgrade it to create-t3-turbo

Link:  https://github.com/t3-oss/create-t3-turbo

**Comment by exectx** [comment]
The main focus of this repo is on `create-t3-app`. Cloudflare also provides the [C3](https://developers.cloudflare.com/pages/get-started/c3/) CLI, which installs the latest `@cloudflare/workers-types` and automatically updates the `tsconfig.json` from any external template, such as those in the [/templates](https://github.com/exectx/t3-cloudflare/tree/main/templates) folder. `create-t3-turbo` focuses on integrating Expo with the T3 stack. It also uses the `create-turbo` CLI, which would be difficult to integrate with `C3`. I may create another repo for `create-t3-turbo`. Regardless thank you for bringing this up.
